# Generated by Django 4.0.6 on 2022-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
